alias ClimbOntario.Catalogue.Import
m=Jason.decode!(File.read!("/workspace/dot-files/knowledge/ontario-gyms/luna-conversion-assignments.json")); allowed=(m["3"]["first_ten"]++m["3"]["remaining_ids"])|>Enum.map(fn x->if is_map(x),do: x["id"], else: x end) |> MapSet.new(); targets=[101,102,103,104,105,106,107,108,109,110,111]; unless Enum.all?(targets, &MapSet.member?(allowed, &1)), do: raise "outside manifest"
put!=fn a,s->case Import.put_listing(a,s) do {:ok,l}->IO.puts("repaired #{l.id}:#{length(l.occurrences)}"); {:error,c}->IO.inspect(c);raise "failed" end end
tz="America/Toronto"
put!.(%{id: 101,venue_id: 18,title: "Rising Climber — Youth Fall Programme",kind: "class",cohorts: ["Ages 6–9 — Wed 17:00–18:00","Ages 6–9 — Wed 18:15–19:15","Ages 6–9 — Thu 17:00–18:00","Ages 10–14 — Thu 18:15–19:15"],timezone: tz,location_kind: "venue",summary: "Weekly coached climbing fundamentals for ages 6–14.",schedule_kind: "recurring",start_date: ~D[2026-09-08],audience: ["youth"],ages: "Ages 6–14.",link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d",link_kind: "registration",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/kids","https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"],checked_on: ~D[2026-09-06],published: false},:preserve)
put!.(%{id: 102,venue_id: 18,title: "Rising Ninja — Youth Fall Programme",kind: "class",cohorts: ["Ages 6–9 — Mon 17:00–18:00","Ages 10–14 — Mon 17:00–18:00","Ages 6–9 — Tue 17:00–18:00","Ages 10–14 — Tue 18:15–19:15","Ages 6–9 — Thu 17:00–18:00","Ages 10–14 — Thu 17:00–18:00","Ages 6–9 — Thu 18:15–19:15"],timezone: tz,location_kind: "venue",summary: "Weekly coached ninja training in balance, agility, strength and coordination for ages 6–14.",schedule_kind: "recurring",start_date: ~D[2026-09-08],audience: ["youth"],ages: "Ages 6–14.",link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d",link_kind: "registration",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/kids","https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"],checked_on: ~D[2026-09-06],published: false},:preserve)
put!.(%{id: 103,venue_id: 18,title: "Adventure Club — Ages 4–5",kind: "class",timezone: tz,location_kind: "venue",summary: "Weekly combined ninja and climbing programme for ages 4–5.",schedule_kind: "recurring",recurrence: "weekly",weekday: 6,start_date: ~D[2026-09-08],start_time: ~T[10:00:00],end_time: ~T[11:00:00],audience: ["youth"],ages: "Ages 4–5.",link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d",link_kind: "registration",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/kids","https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"],checked_on: ~D[2026-09-06],published: false},:preserve)
put!.(%{id: 104,venue_id: 18,title: "Youth Programme Trial Class",kind: "class",timezone: tz,location_kind: "venue",summary: "Trial class introducing youth climbers to climbing or ninja programmes.",schedule_kind: "unscheduled",audience: ["youth"],ages: "Ages 4–14.",link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d",link_kind: "registration",confidence: "confirmed",sources: ["https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"],checked_on: ~D[2026-09-06],published: false},[])
put!.(%{id: 105,venue_id: 18,title: "Rising Ninja — Adult September Start",kind: "class",timezone: tz,location_kind: "venue",summary: "Weekly adult ninja class focused on technique, strength and conditioning.",schedule_kind: "recurring",recurrence: "weekly",weekday: 3,start_date: ~D[2026-09-09],start_time: ~T[18:45:00],end_time: ~T[20:15:00],audience: ["adult"],ages: "Adults.",link: "https://www.steelpeakclimbing.com/adults",link_kind: "event",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/adults"],checked_on: ~D[2026-09-06],published: false},:preserve)
put!.(%{id: 106,venue_id: 18,title: "Intro to Climbing",kind: "class",timezone: tz,location_kind: "venue",summary: "Introductory lesson covering climbing safety, technique, balance and movement for new climbers.",schedule_kind: "unscheduled",audience: ["adult","youth"],ages: "Adults and youth 16+.",link: "https://www.steelpeakclimbing.com/adults",link_kind: "event",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/adults"],checked_on: ~D[2026-09-06],published: false},[])
put!.(%{id: 107,venue_id: 18,title: "Just Climb Nights",kind: "social",timezone: tz,location_kind: "venue",summary: "Monthly social climbing night for climbers of all levels.",schedule_kind: "recurring",recurrence: "monthly",weekday: 3,month_week: 3,start_time: ~T[18:30:00],end_time: ~T[21:30:00],audience: ["family"],link: "https://www.steelpeakclimbing.com/events",link_kind: "event",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/events"],checked_on: ~D[2026-09-06],published: false},:preserve)
put!.(%{id: 108,venue_id: 18,title: "Femme + Them Climb Night",kind: "social",timezone: tz,location_kind: "venue",summary: "Monthly Femme + Them social climbing night for all skill levels.",schedule_kind: "recurring",recurrence: "monthly",weekday: 3,month_week: 1,start_time: ~T[18:30:00],end_time: ~T[21:30:00],audience: ["women","queer"],link: "https://www.steelpeakclimbing.com/events",link_kind: "event",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/events"],checked_on: ~D[2026-09-06],published: false},:preserve)
put!.(%{id: 109,venue_id: 18,title: "Summer Boulder League — 2026",kind: "competition",ocf: false,timezone: tz,location_kind: "venue",summary: "Team bouldering league with weekly tagged-boulder challenges.",schedule_kind: "unscheduled",audience: [],link: "https://www.instagram.com/steelpeakclimbing/reel/Db0xq_LxHCH/",link_kind: "event",confidence: "confirmed",sources: ["https://www.instagram.com/steelpeakclimbing/reel/Db0xq_LxHCH/"],checked_on: ~D[2026-09-06],published: false},[])
put!.(%{id: 110,venue_id: 18,title: "Boulder of the Week Video Challenge",kind: "social",timezone: tz,location_kind: "venue",summary: "Weekly community video challenge featuring the gym’s labelled Boulder of the Week.",schedule_kind: "unscheduled",audience: ["family"],link: "https://www.instagram.com/steelpeakclimbing/",link_kind: "event",confidence: "confirmed",sources: ["https://www.instagram.com/steelpeakclimbing/"],checked_on: ~D[2026-09-06],published: false},[])
put!.(%{id: 111,venue_id: 18,title: "Friday Student Night",kind: "social",timezone: tz,location_kind: "venue",summary: "Weekly Friday climbing, auto-belay and ninja evening for eligible students.",schedule_kind: "recurring",recurrence: "weekly",weekday: 5,start_time: ~T[19:00:00],end_time: ~T[22:00:00],audience: ["youth","adult"],ages: "22 and under.",link: "https://www.steelpeakclimbing.com/events",link_kind: "event",confidence: "confirmed",sources: ["https://www.steelpeakclimbing.com/events"],checked_on: ~D[2026-09-06],published: false},:preserve)
IO.puts("explicit batch 3.3 complete")
