alias ClimbOntario.Catalogue.Import
alias ClimbOntario.Repo
m=Jason.decode!(File.read!("/workspace/dot-files/knowledge/ontario-gyms/luna-conversion-assignments.json")); allowed=MapSet.new((m["1"]["first_ten"]|>Enum.map(& &1["id"]))++m["1"]["remaining_ids"]); targets=MapSet.new([299,300,308,309]); unless MapSet.subset?(targets, allowed), do: raise "manifest target violation"
v=fn n->Repo.get_by!(ClimbOntario.Catalogue.Venue,source_gym_id: n).id end
p=fn a,s->case Import.put_listing(a,s) do {:ok,_}->:ok; {:error,c}->raise "#{a.id}: #{inspect(c.errors)}" end end
p.(%{id: 299,venue_id:  v.(12),title: "OCF Boulder - U17/ U19/ U21 /SENIOR — 2026-10-10",kind: "competition",ocf: true,cohorts: [],summary: "OCF bouldering competition for U17, U19, U21 and Senior categories.",schedule_kind:  "multi_day",start_date:  ~D[2026-10-10],end_date:  ~D[2026-10-11],timezone: "America/Toronto",audience: ["youth","adult"],ages: "U17, U19, U21, Senior",link: "https://www.climbontario.ca/events/ocf-boulder-u17-u19-u21-senior",link_kind:  "event",confidence: "confirmed",caveat: "The athlete schedule is not yet published.",sources: ["https://www.climbontario.ca/events/ocf-boulder-u17-u19-u21-senior","https://www.climbontario.ca/news/ocf-2026-27-competition-season"],checked_on: ~D[2026-09-07],published: false},[%{date: ~D[2026-10-10]},%{date: ~D[2026-10-11]}])
p.(%{id: 300,venue_id:  v.(16),title: "OCF Top Rope Provincials U13/ U15 — 2027-04-24",kind: "competition",ocf: true,cohorts: [],summary: "OCF top-rope provincial competition for U13 and U15 categories.",schedule_kind:  "one_off",start_date:  ~D[2027-04-24],end_date:  ~D[2027-04-24],timezone: "America/Toronto",audience: ["youth"],ages: "U13, U15",link: "https://www.climbontario.ca/events/ocf",link_kind:  "event",confidence: "confirmed",caveat: "The event details are not yet published.",sources: ["https://www.climbontario.ca/events/ocf","https://www.climbontario.ca/news/ocf-2026-27-competition-season"],checked_on: ~D[2026-09-07],published: false},[%{date: ~D[2027-04-24]}])
p.(%{id: 308,venue_id:  v.(27),title: "OCF Boulder - Senior Selection — 2026-12-19",kind: "competition",ocf: true,cohorts: [],summary: "OCF bouldering competition for Senior selection.",schedule_kind:  "one_off",start_date:  ~D[2026-12-19],end_date:  ~D[2026-12-19],timezone: "America/Toronto",audience: ["adult"],ages: "Senior",link: "https://www.climbontario.ca/events/ocf-boulder-senior-selection",link_kind:  "event",confidence: "confirmed",caveat: "The event details are not yet published.",sources: ["https://www.climbontario.ca/events/ocf-boulder-senior-selection","https://www.climbontario.ca/news/ocf-2026-27-competition-season"],checked_on: ~D[2026-09-07],published: false},[%{date: ~D[2026-12-19]}])
p.(%{id: 309,venue_id:  v.(28),title: "OCF Lead Provincials U17/ U19/ U21 — 2027-03-27",kind: "competition",ocf: true,cohorts: [],summary: "OCF lead provincial competition for U17, U19 and U21 categories.",schedule_kind:  "multi_day",start_date:  ~D[2027-03-27],end_date:  ~D[2027-03-28],timezone: "America/Toronto",audience: ["youth"],ages: "U17, U19, U21",link: "https://www.climbontario.ca/events/ocf-lead-provincials-u17-u19-u21",link_kind:  "event",confidence: "confirmed",caveat: "The athlete schedule is not yet published.",sources: ["https://www.climbontario.ca/events/ocf-lead-provincials-u17-u19-u21","https://www.climbontario.ca/news/ocf-2026-27-competition-season"],checked_on: ~D[2026-09-07],published: false},[%{date: ~D[2027-03-27]},%{date: ~D[2027-03-28]}])
IO.puts("repaired OCF 299,300,308,309")
