alias ClimbOntario.Catalogue.Import

put! = fn attrs, sessions ->
  case Import.put_listing(attrs, sessions) do
    {:ok, listing} -> IO.puts("imported #{listing.id} (#{length(listing.occurrences)} occurrences)")
    {:error, changeset} ->
      IO.inspect(changeset, label: "IMPORT FAILED")
      raise "import failed for #{attrs[:id]}"
  end
end

venue = %{aspire: 22, reach: 21}
tz = "America/Toronto"

put!.(%{id: 304, venue_id: venue.aspire, title: "OCF Para Climbing Competition #2 — 2026-11-21",
  kind: "competition", ocf: true, cohorts: [], timezone: tz, location_kind: "venue",
  summary: "Official OCF para climbing competition for adaptive climbers.", schedule_kind: "one_off",
  start_date: ~D[2026-11-21], end_date: ~D[2026-11-21], audience: ["adaptive"],
  link: "https://www.climbontario.ca/events/ocf-para-climbing-competition-2", link_kind: "event",
  confidence: "confirmed", caveat: nil,
  sources: ["https://www.climbontario.ca/events/ocf-para-climbing-competition-2",
    "https://www.climbontario.ca/news/ocf-launches-para-climbing-3-competition-series-for-2026-27-season"],
  checked_on: ~D[2026-09-07], published: false},
  [%{date: ~D[2026-11-21]}])

put!.(%{id: 5, venue_id: venue.aspire, title: "Climbing Team Try-Outs — additional date", kind: "class",
  ocf: nil, cohorts: [], timezone: tz, location_kind: "venue",
  summary: "Additional tryout session for Aspire's youth competitive climbing team.", schedule_kind: "one_off",
  start_date: ~D[2026-09-12], end_date: ~D[2026-09-12], start_time: ~T[14:00:00], end_time: ~T[17:00:00],
  audience: ["youth"], ages: "Ages 7–13; source eligibility bands conflict, so confirm with Aspire.",
  link: "https://app.rockgympro.com/b/?bo=1e3684159a4949708b096db790eb4655", link_kind: "registration",
  confidence: "confirmed", caveat: nil,
  sources: ["https://www.aspireclimbing.com/whitby", "https://www.instagram.com/aspirewhitby/p/Dcod5ZTRUf7/",
    "https://app.rockgympro.com/b/?bo=1e3684159a4949708b096db790eb4655"],
  checked_on: ~D[2026-09-06], published: false},
  [%{date: ~D[2026-09-12], start_time: ~T[14:00:00], end_time: ~T[17:00:00]}])

put!.(%{id: 6, venue_id: venue.aspire, title: "Annual Adaptive Climbing Event", kind: "social",
  ocf: nil, cohorts: [], timezone: tz, location_kind: "venue",
  summary: "Inclusive adaptive climbing event for climbers of varied abilities and experience.", schedule_kind: "one_off",
  start_date: ~D[2026-09-20], end_date: ~D[2026-09-20], start_time: ~T[13:00:00], end_time: ~T[18:00:00],
  audience: ["adaptive", "family"], link: "https://www.aspireclimbing.com/whitby/adaptive-climbing", link_kind: "event",
  confidence: "confirmed", caveat: nil,
  sources: ["https://www.aspireclimbing.com/whitby/adaptive-climbing", "https://www.instagram.com/aspirewhitby/p/Dcb5KtBGj__ /" |> String.replace(" ", "")],
  checked_on: ~D[2026-09-06], published: false},
  [%{date: ~D[2026-09-20], start_time: ~T[13:00:00], end_time: ~T[18:00:00]}])

nemos = [
  {"Tuesday — Sep 15 cohort", ~T[16:30:00], ~T[17:30:00], ~w(2026-09-15 2026-09-22 2026-09-29 2026-10-06 2026-10-13)},
  {"Tuesday — Oct 20 cohort", ~T[16:30:00], ~T[17:30:00], ~w(2026-10-20 2026-10-27 2026-11-03 2026-11-10 2026-11-17)},
  {"Saturday — Sep 19 cohort", ~T[08:45:00], ~T[09:45:00], ~w(2026-09-19 2026-09-26 2026-10-03 2026-10-17 2026-10-24)},
  {"Saturday — Oct 31 cohort", ~T[08:45:00], ~T[09:45:00], ~w(2026-10-31 2026-11-07 2026-11-14 2026-11-21 2026-11-28)},
  {"Sunday — Sep 20 cohort", ~T[08:45:00], ~T[09:45:00], ~w(2026-09-20 2026-09-27 2026-10-04 2026-10-18 2026-10-25)},
  {"Sunday — Nov 1 cohort", ~T[08:45:00], ~T[09:45:00], ~w(2026-11-01 2026-11-08 2026-11-15 2026-11-22 2026-11-29)}
]
# Each named cohort is represented separately; the October/November round uses the same cohort labels.
nemos_sessions = Enum.flat_map(nemos, fn {name, start_time, end_time, dates} ->
  Enum.map(dates, &%{date: &1, cohort: name, start_time: start_time, end_time: end_time})
end)
put!.(%{id: 214, venue_id: venue.aspire, title: "League of Nemos Climbing + Ninja — Fall 2026", kind: "class",
  ocf: nil, cohorts: Enum.map(nemos, &elem(&1, 0)), timezone: tz, location_kind: "venue",
  summary: "Five-class climbing and ninja play cohorts for ages 4–5 with parent participation encouraged.", schedule_kind: "course",
  start_date: ~D[2026-09-15], end_date: ~D[2026-11-29], audience: ["youth", "family"], ages: "Ages 4–5; child must be 4 by the start.",
  link: "https://app.rockgympro.com/b/?bo=998b482f228b4b0f90f585a3e6f0ce36", link_kind: "registration",
  confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=998b482f228b4b0f90f585a3e6f0ce36"],
  checked_on: ~D[2026-09-06], published: false}, nemos_sessions)

ninjas = [
  {"Thursday", ~T[17:00:00], ~T[18:00:00], ~w(2026-09-17 2026-09-24 2026-10-01 2026-10-08 2026-10-15 2026-10-22 2026-10-29 2026-11-05 2026-11-12 2026-11-19)},
  {"Saturday 09:15", ~T[09:15:00], ~T[10:15:00], ~w(2026-09-19 2026-09-26 2026-10-03 2026-10-17 2026-10-24 2026-10-31 2026-11-07 2026-11-14 2026-11-21 2026-11-28)},
  {"Saturday 10:15", ~T[10:15:00], ~T[11:15:00], ~w(2026-09-19 2026-09-26 2026-10-03 2026-10-17 2026-10-24 2026-10-31 2026-11-07 2026-11-14 2026-11-21 2026-11-28)},
  {"Sunday", ~T[11:30:00], ~T[12:30:00], ~w(2026-09-20 2026-09-27 2026-10-04 2026-10-18 2026-10-25 2026-11-01 2026-11-08 2026-11-15 2026-11-22 2026-11-29)}
]
ninja_sessions = Enum.flat_map(ninjas, fn {name, start_time, end_time, dates} ->
  Enum.map(dates, &%{date: &1, cohort: name, start_time: start_time, end_time: end_time})
end)
put!.(%{id: 220, venue_id: venue.aspire, title: "League of Ninjas 1.0 — Fall 2026", kind: "class",
  ocf: nil, cohorts: Enum.map(ninjas, &elem(&1, 0)), timezone: tz, location_kind: "venue",
  summary: "Ten-class weekly ninja obstacle cohorts for ages 5–7.", schedule_kind: "course",
  start_date: ~D[2026-09-17], end_date: ~D[2026-11-29], audience: ["youth"], ages: "Ages 5–7.",
  link: "https://app.rockgympro.com/b/?bo=55766d6f0e384fe597706ead92b098c5", link_kind: "registration",
  confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=55766d6f0e384fe597706ead92b098c5"],
  checked_on: ~D[2026-09-06], published: false}, ninja_sessions)

put!.(%{id: 116, venue_id: venue.reach, title: "Reach Fundamentals — Fall 2026", kind: "class", ocf: nil,
  cohorts: [], timezone: tz, location_kind: "venue", summary: "Six-week coached bouldering course for adults building technique and movement skills.",
  schedule_kind: "course", start_date: ~D[2026-09-15], end_date: ~D[2026-10-20], start_time: ~T[19:30:00], end_time: ~T[21:30:00],
  audience: ["adult"], ages: "18+.", link: "https://app.rockgympro.com/b/?bo=a8d32f34e6d5451b8cd71d50d1ce5bc4", link_kind: "registration",
  confidence: "confirmed", caveat: nil,
  sources: ["https://reachindoorclimbing.ca/adult-lessons", "https://app.rockgympro.com/b/?bo=a8d32f34e6d5451b8cd71d50d1ce5bc4"], checked_on: ~D[2026-09-06], published: false},
  Enum.map(~w(2026-09-15 2026-09-22 2026-09-29 2026-10-06 2026-10-13 2026-10-20), &%{date: &1}))

put!.(%{id: 118, venue_id: venue.reach, title: "Top Rope Belay Lesson and Intro PLUS", kind: "class", ocf: nil,
  cohorts: [], timezone: tz, location_kind: "venue", summary: "Appointment-based top-rope belay instruction for climbers aged 13 and up.",
  schedule_kind: "unscheduled", audience: ["adult", "youth"], ages: "13+.", link: "https://reachindoorclimbing.ca/skill-instruction", link_kind: "event",
  confidence: "confirmed", caveat: "Appointment time is arranged with Reach; no public booking calendar was found.",
  sources: ["https://reachindoorclimbing.ca/skill-instruction"], checked_on: ~D[2026-09-06], published: false}, [])

speed = for {cohort, start_time, end_time} <- [{"U13/U15", ~T[09:00:00], ~T[11:00:00]}, {"U17/U19/U21/Senior", ~T[12:00:00], ~T[15:00:00]}], date <- ~w(2026-09-13 2026-09-20 2026-09-27), do: %{date: date, cohort: cohort, start_time: start_time, end_time: end_time}
put!.(%{id: 120, venue_id: venue.reach, title: "Sunday Speed Training", kind: "class", ocf: nil,
  cohorts: ["U13/U15", "U17/U19/U21/Senior"], timezone: tz, location_kind: "venue",
  summary: "Sunday competition speed training for youth and senior climbers.", schedule_kind: "recurring", audience: ["youth", "adult"],
  ages: "U13, U15, U17, U19, U21 and Senior categories; birth-year bands are shown on the organizer's page.",
  link: "https://reachindoorclimbing.ca/skill-instruction", link_kind: "event", confidence: "confirmed", caveat: nil,
  sources: ["https://reachindoorclimbing.ca/skill-instruction", "https://app.rockgympro.com/b/?bo=55e6411478ca4fc398935bb92511fefc", "https://app.rockgympro.com/b/?bo=4338288e112f489fa3444494aa39a6dd"],
  checked_on: ~D[2026-09-06], published: false}, speed)

put!.(%{id: 121, venue_id: venue.reach, title: "Development Team", kind: "class", ocf: nil, cohorts: [], timezone: tz,
  location_kind: "venue", summary: "Youth competition training focused on movement, tactics and emotional regulation.", schedule_kind: "unscheduled",
  start_date: nil, end_date: nil, start_time: nil, end_time: nil, recurrence: nil, weekday: nil, month_week: nil,
  audience: ["youth"], ages: "Birth years 2013–2017; 5–12 participants.", link: "https://reachindoorclimbing.ca/competitive-teams", link_kind: "event",
  confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/competitive-teams"],
  checked_on: ~D[2026-09-06], published: false}, [])

put!.(%{id: 123, venue_id: venue.reach, title: "Adult Competition Team", kind: "class", ocf: nil, cohorts: [], timezone: tz, location_kind: "venue",
  summary: "Competition training and independent practice for adult climbers entering provincial and recreational events.", schedule_kind: "recurring",
  recurrence: "weekly", weekday: 5, start_time: ~T[18:00:00], end_time: ~T[21:00:00], audience: ["adult"], ages: "Youngest listed birth year: 2007.",
  link: "https://reachindoorclimbing.ca/competitive-teams", link_kind: "event", confidence: "confirmed", caveat: "Season bounds are not published.",
  sources: ["https://reachindoorclimbing.ca/competitive-teams"], checked_on: ~D[2026-09-06], published: false}, :preserve)

IO.puts("batch 3 complete")
put!.(%{id: 7, venue_id: 22, title: "We Are 6 Anniversary — Boulder Scramble Competition", kind: "competition", ocf: false, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "80s-themed anniversary boulder scramble with peer judging for climbers aged 12+.", schedule_kind: "one_off", start_date: ~D[2026-10-03], end_date: nil, start_time: ~T[16:00:00], end_time: ~T[19:00:00], audience: ["youth"], ages: "Ages 12+", link: "https://www.aspireclimbing.com/whitby/anniversary-event", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.aspireclimbing.com/whitby/anniversary-event", "https://www.instagram.com/aspirewhitby/p/DcmFwpzkUNR/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-10-03], start_time: ~T[16:00:00], end_time: ~T[19:00:00]}])
put!.(%{id: 215, venue_id: 22, title: "Buffalos Climbing Program — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly one-hour climbing development for ages 6–7 in five-class blocks.", schedule_kind: "course", start_date: ~D[2026-09-17], end_date: ~D[2026-11-29], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 6-7", link: "https://app.rockgympro.com/b/?bo=b14c06586a1d451d90ba44b3c2c115ca", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=b14c06586a1d451d90ba44b3c2c115ca"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 216, venue_id: 22, title: "Rattlesnakes Climbing Program — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly one-hour climbing development for ages 8-10 over ten classes.", schedule_kind: "course", start_date: ~D[2026-09-15], end_date: ~D[2026-11-29], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 8-10", link: "https://app.rockgympro.com/b/?bo=ac3ca75f5ba44f34a30a1a5c15e3033a", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=ac3ca75f5ba44f34a30a1a5c15e3033a"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 217, venue_id: 22, title: "Kelsos Climbing Program — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly 90-minute climbing development for ages 11-14 over ten classes.", schedule_kind: "course", start_date: ~D[2026-09-15], end_date: ~D[2026-11-19], start_time: ~T[19:00:00], end_time: ~T[20:30:00], audience: ["youth"], ages: "Ages 11-14", link: "https://app.rockgympro.com/b/?bo=5c04f1fafc6b48a9b73bf1f1464709f1", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=5c04f1fafc6b48a9b73bf1f1464709f1"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 218, venue_id: 22, title: "Youth Adaptive Climbing — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Five two-hour sessions for ages 6-13 with physical, cognitive, sensory or developmental disabilities", schedule_kind: "course", start_date: ~D[2026-09-27], end_date: ~D[2026-11-01], start_time: ~T[17:00:00], end_time: ~T[19:00:00], audience: ["youth", "adaptive"], ages: "Ages 6-13", link: "https://app.rockgympro.com/b/?bo=6c3eff4068bf421a8af4436f1cb1e26c", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.aspireclimbing.com/whitby", "https://app.rockgympro.com/b/?bo=6c3eff4068bf421a8af4436f1cb1e26c"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 219, venue_id: 22, title: "Teen Night — Fall 2026 climbing series", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Ten two-hour social sessions for teens exploring bouldering, auto-belays and top rope, with a top-rope knots and belay lesson in week 4.", schedule_kind: "course", start_date: ~D[2026-09-18], end_date: ~D[2026-11-27], start_time: ~T[17:30:00], end_time: ~T[19:30:00], audience: [], ages: nil, link: "https://app.rockgympro.com/b/?bo=620d3458de284c4f9d7eabb02635ddf7", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=620d3458de284c4f9d7eabb02635ddf7"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 221, venue_id: 22, title: "League of Ninjas 2.0 — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly one-hour ninja obstacle training for ages 8-10 developing balance, coordination and strength", schedule_kind: "course", start_date: ~D[2026-09-17], end_date: ~D[2026-11-29], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 8-10", link: "https://app.rockgympro.com/b/?bo=350ead321acd47e89714cf77c05fdc18", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=350ead321acd47e89714cf77c05fdc18"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 222, venue_id: 22, title: "League of Ninjas 3.0 — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly 90-minute ninja training for ages 11-14 with advanced obstacles, endurance and agility", schedule_kind: "course", start_date: ~D[2026-09-15], end_date: ~D[2026-11-17], start_time: ~T[17:15:00], end_time: ~T[18:45:00], audience: ["youth"], ages: "Ages 11-14", link: "https://app.rockgympro.com/b/?bo=e3d642737a304e1f8f9bd4fb49665727", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=e3d642737a304e1f8f9bd4fb49665727"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 223, venue_id: 22, title: "Adaptive Climbing Try-Us-Out Nights", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Monthly adaptive climbing evening for all ages and skill levels: climbing, socializing and equipment introduction with qualified staff.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["adaptive"], ages: "All ages", link: "https://app.rockgympro.com/b/?bo=2da17faea5f84ffe8be7f35b41ee17f6", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.aspireclimbing.com/whitby", "https://www.aspireclimbing.com/adaptiveclimbing", "https://app.rockgympro.com/b/?bo=2da17faea5f84ffe8be7f35b41ee17f6"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 224, venue_id: 22, title: "Competitive Climbing Team — 2026/2027 season", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Nine-month competitive training program for youth competing at local through national events under OCF/CEC.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://app.rockgympro.com/b/?bw=a696d72cca474d99a3aae7ddc27fc283", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bw=a696d72cca474d99a3aae7ddc27fc283"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 305, venue_id: 22, title: "OCF Top Rope U11/ U13/ U15 — 2027-02-13", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "OCF top rope competition for U11, U13 and U15 categories.", schedule_kind: "one_off", start_date: ~D[2027-02-13], end_date: ~D[2027-02-13], start_time: nil, end_time: nil, audience: ["youth"], ages: "U11, U13, U15", link: "https://www.climbontario.ca/events/ocf-tope-rope-u11-u13-u15", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-tope-rope-u11-u13-u15", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2027-02-13]}])
put!.(%{id: 115, venue_id: 21, title: "Youth Recreational Lessons — Session 1 Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly age-grouped climbing lessons for ages 4-17 with on- and off-wall activities.", schedule_kind: "course", start_date: ~D[2026-09-15], end_date: ~D[2026-12-06], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 4-17", link: "https://reachindoorclimbing.ca/youth-lessons", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/youth-lessons", "https://www.instagram.com/reachindoorclimbing/p/DcjiZMQsT-p/", "https://app.rockgympro.com/b/?bo=6a0a8580f4c147d18d17ed1f271fdf8e", "https://app.rockgympro.com/b/?bo=2634b7eb36564b3c94f5b00b620a4d7c", "https://app.rockgympro.com/b/?bo=f6861741c30a4fde8cba17cf60220fc8", "https://app.rockgympro.com/b/?bo=0b5f49c3fd66440e8be9676469774a83", "https://app.rockgympro.com/b/?bo=3fe7e8bdd10c4957aaa52cf187245905", "https://app.rockgympro.com/b/?bo=6f7afc5e78b642cca995beac172742fe", "https://app.rockgympro.com/b/?bo=c4f201ea01ec422db60b9dfa9e686b2a", "https://app.rockgympro.com/b/?bo=68d9e0d7e1c94ded9e35f6fb0a53b548", "https://app.rockgympro.com/b/?bo=60b7e113e76149cc843f2818fe123c74", "https://app.rockgympro.com/b/?bo=8073f233c0174ab28c54d06a9f152784", "https://app.rockgympro.com/b/?bo=c9edc790af954f5883ee994151480d38"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 117, venue_id: 21, title: "Reach Progression — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Six-week intermediate bouldering course for adults 18+ with weekly training plans and healthy climbing habits.", schedule_kind: "course", start_date: ~D[2026-09-17], end_date: ~D[2026-10-22], start_time: ~T[19:30:00], end_time: ~T[21:30:00], audience: ["adult"], ages: "Ages 18+", link: "https://app.rockgympro.com/b/?bo=42f3fd1991fa4a7292f2acaff97dafd6", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/adult-lessons", "https://app.rockgympro.com/b/?bo=42f3fd1991fa4a7292f2acaff97dafd6"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 119, venue_id: 21, title: "Lead Climb and Belay Lesson", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Two 3-hour lessons over two days covering safe clipping, lead climbing, falling and lead belaying.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 16+", link: "https://reachindoorclimbing.ca/skill-instruction", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/skill-instruction"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 122, venue_id: 21, title: "Performance Team", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Team for experienced youth competition climbers with age-specific U13/15 and U17/19 skill work in a shared practice.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: "Born 2009-2013", link: "https://reachindoorclimbing.ca/competitive-teams", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/competitive-teams"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 124, venue_id: 21, title: "Private, Semi-Private and Group Coaching", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Coaching on personal goals, training plans, technique and confidence.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://reachindoorclimbing.ca/private-lessons", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/private-lessons"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 125, venue_id: 21, title: "Therapeutic and Adaptive Climbing Sessions", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Occupational therapist-supported climbing for children and adults, working toward individual goals on and off the wall with adaptations for physical, cognitive and learning needs.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth", "adult", "adaptive"], ages: "Children and adults", link: "https://reachindoorclimbing.ca/therapy%2Fadaptive-climbing", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/therapy%2Fadaptive-climbing"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 126, venue_id: 21, title: "Friday Night Onsight — October 2026", kind: "competition", ocf: false, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Recreational competition climbing night", schedule_kind: "one_off", start_date: ~D[2026-10-02], end_date: ~D[2026-10-02], start_time: ~T[18:00:00], end_time: ~T[21:00:00], audience: [], ages: nil, link: "https://app.rockgympro.com/b/?bo=a30bb04fadbd471fb97cb9060422bdcc", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/reachindoorclimbing/p/Dcl5K0FOvch/", "https://linktr.ee/reachindoorclimbing", "https://app.rockgympro.com/b/?bo=a30bb04fadbd471fb97cb9060422bdcc"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-10-02], start_time: ~T[18:00:00], end_time: ~T[21:00:00]}])
put!.(%{id: 302, venue_id: 21, title: "OCF Para Climbing Competition #1 — 2026-09-26", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "OCF para climbing competition, first of the season.", schedule_kind: "one_off", start_date: ~D[2026-09-26], end_date: ~D[2026-09-26], start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.climbontario.ca/events/ocf-para-climbing-competition-1", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-para-climbing-competition-1", "https://www.climbontario.ca/news/ocf-2026-27-competition-season", "https://www.climbontario.ca/news/ocf-launches-para-climbing-3-competition-series-for-2026-27-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2026-09-26]}])
put!.(%{id: 303, venue_id: 21, title: "OCF Boulder U11/ U13/ U15 — 2026-12-12", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Two-day OCF bouldering competition: U11 and U13 categories on Saturday, U15 on Sunday.", schedule_kind: "multi_day", start_date: ~D[2026-12-12], end_date: ~D[2026-12-13], start_time: nil, end_time: nil, audience: ["youth"], ages: "U11, U13, U15", link: "https://www.climbontario.ca/events/ocf-boulder-u11-u13-u15", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-boulder-u11-u13-u15", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [~D[2026-12-12], ~D[2026-12-13] ])
put!.(%{id: 101, venue_id: 18, title: "Rising Climber — Youth Fall Programme", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly coached climbing fundamentals for ages 6–14.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 6-14", link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.steelpeakclimbing.com/kids", "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 102, venue_id: 18, title: "Rising Ninja — Youth Fall Programme", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly coached balance, agility, strength and coordination on ninja obstacles for ages 6-14", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 6-14", link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.steelpeakclimbing.com/kids"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 103, venue_id: 18, title: "Adventure Club — Ages 4–5", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Combined ninja and climbing program for ages 4-5", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 4-5", link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.steelpeakclimbing.com/kids", "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 104, venue_id: 18, title: "Youth Programme Trial Class", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "45-minute trial for ages 4-14 to meet instructors and sample climbing or ninja", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 4-14", link: "https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=54f49b944146493f94134894dea4ab1d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 105, venue_id: 18, title: "Rising Ninja — Adult September Start", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly adult ninja class covering technique, strength and conditioning.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["adult"], ages: "Adults", link: "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=1b3d48f4d348400f98d8bb854ce553ca&mode=p", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.steelpeakclimbing.com/adultprograms", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=1b3d48f4d348400f98d8bb854ce553ca&mode=p"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 106, venue_id: 18, title: "Intro to Climbing", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Introductory lesson for new adult climbers and youth 16+ covering risk reduction, hand and foot technique, balance and movement.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth", "adult"], ages: "Adults and youth 16+", link: "https://app.rockgympro.com/b/widget/?a=list&widget_guid=94d5cdd151774fbabe100dbd8aabd2b3&mode=p", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.steelpeakclimbing.com/adultprograms", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=ba624bad492d414b8a3c3d85e143f738&mode=p", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=184eeae7cc224f9ea64ab0ce5985d968&mode=p"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 107, venue_id: 18, title: "Just Climb Nights", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Monthly social climbing night for all levels, hosted by Rudy and Stephanie Ly.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://docs.google.com/forms/d/e/1FAIpQLSdv4AmNP0JP6NB66eivO8_ICoRCnOQiYWUTH-LNkjCm3WGjXA/viewform", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/steelpeakclimbing/p/DW4PCN9kbxJ/", "https://docs.google.com/forms/d/e/1FAIpQLSdv4AmNP0JP6NB66eivO8_ICoRCnOQiYWUTH-LNkjCm3WGjXA/viewform", "https://www.instagram.com/steelpeakclimbing/reel/Dcl41FcxYd2/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 108, venue_id: 18, title: "Femme + Them Climb Night", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Monthly Femme + Them social climbing night for all skill levels, hosted by Stephanie Ly.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://docs.google.com/forms/d/e/1FAIpQLScIstlGScsgDYVkTati8eHA3q1QoVtACBF0TgmcXpD11KylNA/viewform", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/steelpeakclimbing/p/DWjLipakfuZ/", "https://docs.google.com/forms/d/e/1FAIpQLScIstlGScsgDYVkTati8eHA3q1QoVtACBF0TgmcXpD11KylNA/viewform", "https://www.instagram.com/steelpeakclimbing/reel/Dc1hDsUtp_7/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 109, venue_id: 18, title: "Summer Boulder League — 2026", kind: "competition", ocf: false, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Team bouldering league with weekly tagged-boulder challenges for members.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.instagram.com/steelpeakclimbing/reel/Db0xq_LxHCH/", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/steelpeakclimbing/reel/Db0xq_LxHCH/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 110, venue_id: 18, title: "Boulder of the Week Video Challenge", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly video challenge: film your send or fall on the labelled Boulder of the Week and tag the gym in an Instagram reel.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://www.instagram.com/steelpeakclimbing/p/DEVJ5OluDZc/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/steelpeakclimbing/p/DEVJ5OluDZc/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 111, venue_id: 18, title: "Friday Student Night", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Discounted Friday night climbing, auto-belay and ninja access for youth-rate eligible people 22 and under.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: "Ages 22 and under", link: "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=6dc8afb6370642919ac7d806f949d47c&mode=p", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.steelpeakclimbing.com/pricing", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=6dc8afb6370642919ac7d806f949d47c&mode=p"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 78, venue_id: 3, title: "Bouldering 101", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "One-hour intro class covering safety, falling, problem reading and basic technique", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.rockonclimbing.ca/bouldering-101-class", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/bouldering-101-class", "https://www.rockonclimbing.ca/promos"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 79, venue_id: 3, title: "Bouldering 102 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Five-week beginner bouldering program of weekly two-hour classes", schedule_kind: "one_off", start_date: ~D[2026-09-12], end_date: nil, start_time: ~T[13:00:00], end_time: ~T[15:00:00], audience: [], ages: nil, link: "https://www.instagram.com/rockon_to/p/DchXH4rtxR3/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/rockon_to/p/DchXH4rtxR3/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-12], start_time: ~T[13:00:00], end_time: ~T[15:00:00]}])
put!.(%{id: 80, venue_id: 3, title: "Bouldering 201", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Five-week technique and plateau-breaking course for climbers beyond 101, with coach/setter Jeremy Yang.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.rockonclimbing.ca/bouldering-101-class", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/bouldering-101-class"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 81, venue_id: 3, title: "Private Climbing Coaching", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Customized one-on-one climbing coaching in one-hour sessions, tailored to individual abilities.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.rockonclimbing.ca/bouldering-101-class", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/bouldering-101-class"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 82, venue_id: 3, title: "Community Trivia Nights", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Community trivia night with host Kels.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://www.rockonclimbing.ca/promos", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/promos", "https://www.instagram.com/rockon_to/p/DW2Gx9rgWY_/", "https://www.instagram.com/rockon_to/p/DZYWZp_BssD/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 83, venue_id: 3, title: "Mat Leave Mondays", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Parents bring their babies to climb and connect with other climbing parents.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://www.rockonclimbing.ca/promos", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/promos"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 84, venue_id: 3, title: "Community Climb with Jenny", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Casual climbing alongside coach Jenny at her weekly session.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://www.rockonclimbing.ca/promos", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/promos"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 85, venue_id: 3, title: "Student Saturdays", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Discounted student day passes every Saturday.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://www.rockonclimbing.ca/promos", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.rockonclimbing.ca/promos"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 71, venue_id: 2, title: "Core Elements — Intro to Bouldering", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "90-minute beginner class covering footwork, dynamic movement and body positioning.", schedule_kind: "one_off", start_date: ~D[2026-09-06], end_date: ~D[2026-09-06], start_time: ~T[16:00:00], end_time: ~T[17:30:00], audience: [], ages: nil, link: "https://ethosclimbing.rphq.com/ethos/programs/meet-climbing", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.ethosclimbing.ca/instruction", "https://ethosclimbing.rphq.com/ethos/programs/meet-climbing"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-06], start_time: ~T[16:00:00], end_time: ~T[17:30:00]}])
put!.(%{id: 72, venue_id: 2, title: "Kilter Class", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Intro and experienced tracks alternate weekly.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://ethosclimbing.rphq.com/ethos/n/classes", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.ethosclimbing.ca/instruction", "https://ethosclimbing.rphq.com/ethos/programs/Kilter%20Class?date=2026-09-12", "https://ethosclimbing.rphq.com/ethos/programs/kilter-class?date=2026-09-19"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 73, venue_id: 2, title: "Sunday School — Coached Climbing", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Coached Sunday climbing session with project support and technique coaching.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://ethosclimbing.rphq.com/ethos/n/classes", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.ethosclimbing.ca/instruction", "https://ethosclimbing.rphq.com/ethos/programs/sunday-school?date=2026-09-13", "https://ethosclimbing.rphq.com/ethos/programs/sunday-school-2?date=2026-09-20", "https://www.instagram.com/ethosclimbinggym/reel/DckDPY-MbAO/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 74, venue_id: 2, title: "Elevate — Goal Setting and Session Planning Clinic", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Clinic on setting climbing goals and planning sessions, hosted by the Elevate club for women and gender-diverse climbers", schedule_kind: "one_off", start_date: ~D[2026-09-14], end_date: ~D[2026-09-14], start_time: ~T[19:00:00], end_time: ~T[21:00:00], audience: [], ages: nil, link: "https://www.instagram.com/ethosclimbinggym/p/DcuF_rSxt1q/", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/ethosclimbinggym/p/DcuF_rSxt1q/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-14], start_time: ~T[19:00:00], end_time: ~T[21:00:00]}])
put!.(%{id: 75, venue_id: 2, title: "Ethos Queer Climb", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly queer social climbing club for all experience levels, led by Alanna: group warm-up, climbing, meeting people and shared snacks.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["queer"], ages: nil, link: "https://www.instagram.com/ethosclimbinggym/p/Dbq_y-NGZIP/", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/ethosclimbinggym/p/Dbq_y-NGZIP/", "https://www.ethosclimbing.ca/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 76, venue_id: 2, title: "Queer Climb Toronto Meetup — September2026", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "All-level queer/trans bouldering meetup with Queer Climb Toronto.", schedule_kind: "one_off", start_date: ~D[2026-09-13], end_date: ~D[2026-09-13], start_time: ~T[14:00:00], end_time: ~T[17:00:00], audience: ["queer"], ages: nil, link: "https://portal.ethosclimbing.ca/l?t=JoZPu2TszEKxxBVQ", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/ethosclimbinggym/p/DceSVV9ykzH/", "https://portal.ethosclimbing.ca/l?t=JoZPu2TszEKxxBVQ"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-13], start_time: ~T[14:00:00], end_time: ~T[17:00:00]}])
put!.(%{id: 77, venue_id: 2, title: "Private Climbing Coaching with Brad", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "One-on-one goal-setting and tailored climbing coaching with the head setter/coach, for newer or experienced climbers.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.ethosclimbing.ca/instruction", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.ethosclimbing.ca/instruction"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 145, venue_id: 39, title: "Youth Program — 2026–2027 Session 1", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekly ability-grouped coached climbing for ages 6-18 with techniques and drills, led by youth competitive-team and staff coaches.", schedule_kind: "course", start_date: ~D[2026-08-31], end_date: ~D[2026-11-08], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 6-18", link: "https://coyoterockgym.ca/youth-climbing-courses-2/youth-climbing-courses/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://coyoterockgym.ca/youth-climbing-courses-2/youth-climbing-courses/", "https://app.rockgympro.com/b/?bo=0aa0b90d929f47bdbbd1125d50a81224"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 146, venue_id: 39, title: "Adult Intro to Climbing — Session 1 Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Eight-week beginner course for ages 18+ covering fundamentals, movement, safety, terminology, top-rope belaying and safe bouldering falls.", schedule_kind: "course", start_date: ~D[2026-09-17], end_date: ~D[2026-11-05], start_time: ~T[18:30:00], end_time: ~T[20:30:00], audience: ["adult"], ages: "Ages 18+", link: "https://app.rockgympro.com/b/?bo=86d86066d42a42f58d7e499cc0b6f442", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://coyoterockgym.ca/courses/adult-climbing-course/", "https://app.rockgympro.com/b/?bo=86d86066d42a42f58d7e499cc0b6f442", "https://coyoterockgym.ca/first-visit/hours/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 147, venue_id: 39, title: "Intro Plus Lessons — Saturday and Sunday", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Two-hour weekend intro lesson for ages 14+ new to indoor climbing: belaying, tie-in, technique, terminology, holds and bouldering.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 14+", link: "https://coyoterockgym.ca/courses/intro-plus-course/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://coyoterockgym.ca/courses/intro-plus-course/", "https://app.rockgympro.com/b/?bo=5868b0be50664ba1807f65a869082a79", "https://app.rockgympro.com/b/?bo=1ff9686ce9534ad3ad17c5c0e16aaa9d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 148, venue_id: 39, title: "Lead Climbing Course — Tuesday/Thursday", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Indoor lead climbing course with Dan for pairs, one instructor to two students.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://coyoterockgym.ca/courses/lead-courses/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://coyoterockgym.ca/courses/lead-courses/", "https://coyoterockgym.ca/first-visit/hours/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 205, venue_id: 39, title: "Drytool showcase and information session", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Showcase and information session about drytooling ahead of the November event.", schedule_kind: "one_off", start_date: ~D[2026-09-11], end_date: ~D[2026-09-11], start_time: ~T[18:00:00], end_time: ~T[21:00:00], audience: [], ages: nil, link: "https://www.instagram.com/thecoyoterockgym/p/Db_Rs5tt1w2/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/thecoyoterockgym/p/Db_Rs5tt1w2/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-11], start_time: ~T[18:00:00], end_time: ~T[21:00:00]}])
put!.(%{id: 206, venue_id: 39, title: "Drytool Weekend — November 2026 announcement", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Weekend-long drytooling event returning in November", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.instagram.com/thecoyoterockgym/p/Db_Rs5tt1w2/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/thecoyoterockgym/p/Db_Rs5tt1w2/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 207, venue_id: 39, title: "Pre-competitive team — 2026–2027", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Twice-weekly youth team developing toward competitive climbing with technical training, plus about 4-5 weekend competitions a year.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 8-17", link: "https://www.instagram.com/thecoyoterockgym/p/DZLybHfJQr3/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/thecoyoterockgym/p/DZLybHfJQr3/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 26, venue_id: 6, title: "School of Rock — Fall 2026 semester", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Semester-long youth climbing in four streams: Pebble (6-7), Rock Club (8-10), Rec Team (11-13) and Dev Team (13-17).", schedule_kind: "course", start_date: ~D[2026-09-08], end_date: ~D[2027-01-31], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 6-17", link: "https://www.rockoasis.com/schoolofrock", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.rockoasis.com/", "https://www.rockoasis.com/schoolofrock", "https://app.rockgympro.com/b/?bo=c2f918f2d8b54c07b688c8966a2f675c", "https://app.rockgympro.com/b/?bo=7e12047bf79f4ec8b51681cf4405bd5d", "https://app.rockgympro.com/b/?bo=f08aeabfafda4e90b3347472a7b9d962", "https://app.rockgympro.com/b/?bo=26b6548fe3f54d2e96b2ecffc6082436"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 233, venue_id: 6, title: "Bulges & Boulders — September 2026 Rock Oasis meetups", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Queer-inclusive community climb for all levels with top rope and bouldering, a gym orientation for new climbers and an optional dinner afterwards.", schedule_kind: "one_off", start_date: ~D[2026-09-08], end_date: nil, start_time: ~T[18:00:00], end_time: ~T[20:30:00], audience: ["queer"], ages: nil, link: "https://www.instagram.com/bulgesandboulders/p/DcvwNu4Ee66/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/bulgesandboulders/p/DcvwNu4Ee66/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-08], start_time: ~T[18:00:00], end_time: ~T[20:30:00]}])
put!.(%{id: 254, venue_id: 6, title: "PA Day Camps — 2026–2027 dates coming soon", kind: "camp", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Full-day climbing camp on TDSB PA days for ages 6+.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 6+", link: "https://www.rockoasis.com/camps", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.rockoasis.com/camps"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 255, venue_id: 6, title: "School of Rock — Semester 2 February–June 2027 announcement", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Second semester of the youth School of Rock program (after-school and weekend cohorts)", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.rockoasis.com/schoolofrock", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.rockoasis.com/schoolofrock", "https://app.rockgympro.com/b/?bo=f08aeabfafda4e90b3347472a7b9d962"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 256, venue_id: 6, title: "Boulder 101 — September 2026 lessons", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "One-hour beginner bouldering class for ages 14+ covering movement, footwork, hand placement, body position and route reading, plus a boulder orientation.", schedule_kind: "one_off", start_date: ~D[2026-09-08], end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 14+", link: "https://app.rockgympro.com/b/?bo=c3d2db1db2cc4045bd31a854b963fd25", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.rockoasis.com/lessons-2", "https://app.rockgympro.com/b/?bo=c3d2db1db2cc4045bd31a854b963fd25"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-08]}])
put!.(%{id: 257, venue_id: 6, title: "Top Rope 101 — September 2026 lessons", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "90-minute harness, knot and belay lesson with facility tour and orientations.", schedule_kind: "one_off", start_date: ~D[2026-09-07], end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 14+ to belay", link: "https://app.rockgympro.com/b/?bo=0332f6c74df94c1ca221a1f86ae675fc", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.rockoasis.com/lessons-2", "https://app.rockgympro.com/b/?bo=0332f6c74df94c1ca221a1f86ae675fc"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-07]}])
put!.(%{id: 132, venue_id: 24, title: "Adult Climbing Course — Rolling Four Weeks", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Technique-focused four-week course for new and returning climbers seeking efficiency and progression.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["adult"], ages: "Adults", link: "https://pinnacleindoorclimbing.com/program-sign-up/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://pinnacleindoorclimbing.com/lessons/", "https://joeys.lilypadpos.app/public/onlineproductsales/sales2.php?ptid=126,77"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 133, venue_id: 24, title: "Pinnacle Climbing Academy — Rolling Youth Programme", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Beginner-friendly 90-minute weekly youth climbing class building foundations and confidence through play.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 4-13", link: "https://joeys.lilypadpos.app/public/onlineproductsales/sales2.php?ptid=126,77", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://pinnacleindoorclimbing.com/youth-climbing-course/", "https://joeys.lilypadpos.app/public/onlineproductsales/sales2.php?ptid=126,77", "https://www.instagram.com/pinnacleindoorclimbing/reel/Dbl-T01Pvfg/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 134, venue_id: 24, title: "Pinnacle Prep Team — September to May", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Nine-month twice-weekly youth team for ages 8-18 with more than basic climbing knowledge: structured skill and strength work and mock competitions as a pathway to the comp team.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 8-18", link: "https://pinnacleindoorclimbing.com/youth-climbing-course/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://pinnacleindoorclimbing.com/youth-climbing-course/", "https://www.instagram.com/pinnacleindoorclimbing/reel/Dbl-T01Pvfg/", "https://joeys.lilypadpos.app/public/onlineproductsales/sales2.php?ptid=126,77"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 135, venue_id: 24, title: "Pinnacle Comp Team — Invitation/Tryout", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Invitation-only competitive youth team for ages 7-17 training bouldering, sport and speed for local to national competition, plus technique, strength, endurance and mental focus.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 7-17", link: "https://pinnacleindoorclimbing.com/youth-climbing-course/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://pinnacleindoorclimbing.com/youth-climbing-course/", "https://www.instagram.com/pinnacleindoorclimbing/reel/Dbl-T01Pvfg/"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 306, venue_id: 24, title: "OCF Top Rope U11/ U13/ U15 — 2026-10-25", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "OCF top rope competition for U11, U13 and U15 categories.", schedule_kind: "one_off", start_date: ~D[2026-10-25], end_date: ~D[2026-10-25], start_time: nil, end_time: nil, audience: ["youth"], ages: "U11, U13, U15", link: "https://www.climbontario.ca/events/ocf-u11-u13-u15-tope-rope", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-u11-u13-u15-tope-rope", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2026-10-25]}])
put!.(%{id: 307, venue_id: 24, title: "OCF SPEED U13/ U15 U17/ U19/ U21 /SR — 2026-11-08", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "OCF speed climbing competition for U13, U15, U17, U19, U21 and Senior categories.", schedule_kind: "one_off", start_date: ~D[2026-11-08], end_date: ~D[2026-11-08], start_time: nil, end_time: nil, audience: ["youth"], ages: "U13 to Senior", link: "https://www.climbontario.ca/events/ocf-speed-u11-u13-u15-u17-u19-u21-sr", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-speed-u11-u13-u15-u17-u19-u21-sr", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2026-11-08]}])
put!.(%{id: 1, venue_id: 38, title: "15th Anniversary Party", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Gym anniversary celebration with an auto-belay competition, climbing challenges, a vendor market and other activities.", schedule_kind: "one_off", start_date: ~D[2026-09-12], end_date: nil, start_time: ~T[12:00:00], end_time: ~T[17:00:00], audience: ["family"], ages: nil, link: "https://www.instagram.com/grr_kit/p/DczGft_z0Ru/", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/grr_kit/p/DczGft_z0Ru/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-12], start_time: ~T[12:00:00], end_time: ~T[17:00:00]}])
put!.(%{id: 2, venue_id: 38, title: "Rubble Rebels — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Ten-week youth climbing program in four time/age cohorts.", schedule_kind: "course", start_date: ~D[2026-09-14], end_date: ~D[2026-11-23], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 7-17", link: "https://grandriverrocks.com/kitchener/youth/rubble-rebels-2/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://grandriverrocks.com/location/kitchener/rubble-rebels/", "https://grandriverrocks.com/kitchener/youth/rubble-rebels-2/", "https://www.eventbrite.ca/e/1997566462061", "https://www.eventbrite.ca/e/1997567080912", "https://www.eventbrite.ca/e/1997567399866", "https://www.eventbrite.ca/e/1997567841186"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 210, venue_id: 38, title: "Rock Rascals — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Beginner climbing techniques and terminology for ages 5-8 through games and instruction.", schedule_kind: "course", start_date: ~D[2026-09-19], end_date: ~D[2026-11-07], start_time: ~T[08:00:00], end_time: ~T[10:00:00], audience: ["youth"], ages: "Ages 5-8", link: "https://app.rockgympro.com/b/?bo=15767807522d4ee1a7b93d00ab82dc52", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://grandriverrocks.com/kitchener/youth/rock-rascals/", "https://app.rockgympro.com/b/?bo=15767807522d4ee1a7b93d00ab82dc52"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 211, venue_id: 38, title: "Development Team — Fall 2026 training", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Development program for ages 9-17 interested in competitive climbing", schedule_kind: "course", start_date: ~D[2026-09-14], end_date: ~D[2026-11-23], start_time: ~T[18:30:00], end_time: ~T[21:00:00], audience: ["youth"], ages: "Ages 9-17", link: "https://grandriverrocks.com/kitchener/youth/development-team/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://grandriverrocks.com/kitchener/youth/development-team/", "https://docs.google.com/forms/d/e/1FAIpQLSewTq8DECMBN0skhjoZqvaVZMZhTiV-1k0lALxxkJ3_w28UVQ/viewform?usp=header"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 212, venue_id: 38, title: "Level 1 Intro Aerial Silks ages 8–15 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Introductory aerial silks course for ages 8-15, no experience needed.", schedule_kind: "course", start_date: ~D[2026-09-13], end_date: ~D[2026-10-11], start_time: ~T[14:30:00], end_time: ~T[15:30:00], audience: ["youth"], ages: "Ages 8-15", link: "https://app.rockgympro.com/b/?bo=da506ed7386a4a9986506ea4d2a736cd", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://grandriverrocks.com/kitchener/classes/aerial-silks-8-15/", "https://app.rockgympro.com/b/?bo=da506ed7386a4a9986506ea4d2a736cd"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 213, venue_id: 38, title: "Level 2 Beginner Aerial Silks ages 8–15 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Beginner aerial silks for ages 8-15 who have completed an intro series (footlock from the ground, inversion in a hip-height knot).", schedule_kind: "course", start_date: ~D[2026-09-13], end_date: ~D[2026-10-11], start_time: ~T[15:45:00], end_time: ~T[16:45:00], audience: ["youth"], ages: "Ages 8-15", link: "https://app.rockgympro.com/b/?bo=8992df6eb5404706b94a10cfd2d1f52d", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://grandriverrocks.com/kitchener/classes/aerial-silks-8-15/", "https://app.rockgympro.com/b/?bo=8992df6eb5404706b94a10cfd2d1f52d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 30, venue_id: 14, title: "Blaze — September–October 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Choose one cohort.", schedule_kind: "course", start_date: ~D[2026-09-14], end_date: ~D[2026-10-26], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 5-6", link: "https://app.rockgympro.com/b/?&bo=fc35d5c9c81c4331b50dcd2fe6808813", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://hubclimbing.com/markham/youth/youth-recreational-team/", "https://app.rockgympro.com/b/?&bo=fc35d5c9c81c4331b50dcd2fe6808813"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 260, venue_id: 14, title: "Dragon — September–October 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Six-week program of 90-minute climbing lessons, games, movement and teamwork for ages 7-9.", schedule_kind: "course", start_date: ~D[2026-09-14], end_date: ~D[2026-10-26], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 7-9", link: "https://app.rockgympro.com/b/?bo=d5fae0bb18f14f27858d5f84c9984a6d", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=d5fae0bb18f14f27858d5f84c9984a6d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 261, venue_id: 14, title: "Wyvern — September–October 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Six-week program of 90-minute climbing lessons, games, movement and teamwork for ages 9-11.", schedule_kind: "course", start_date: ~D[2026-09-14], end_date: ~D[2026-10-26], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 9-11", link: "https://app.rockgympro.com/b/?bo=74212368ad1c48eca4b6cb84af19d314", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=74212368ad1c48eca4b6cb84af19d314"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 262, venue_id: 14, title: "Leviathan — September–October 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Six-week program of 90-minute climbing lessons, games, movement and teamwork for ages 12-14.", schedule_kind: "course", start_date: ~D[2026-09-14], end_date: ~D[2026-10-26], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 12-14", link: "https://app.rockgympro.com/b/?bo=5c8ac5d3d32246fcbd85e5dc41ba5c7c", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=5c8ac5d3d32246fcbd85e5dc41ba5c7c"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 263, venue_id: 14, title: "Teen — September–October 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Six-week program of 90-minute climbing lessons, games, movement and teamwork for ages 13-17.", schedule_kind: "course", start_date: ~D[2026-09-17], end_date: ~D[2026-10-24], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 13-17", link: "https://app.rockgympro.com/b/?bo=3db7de14486b4edf99ab65b6e638ed64", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=3db7de14486b4edf99ab65b6e638ed64"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 154, venue_id: 41, title: "Recreational Climbing Ages 5–7 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Seven-week youth programme for ages 5-7 building confidence, motor skills and collaboration through bouldering and auto-belays, one hour weekly", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 5-7", link: "https://app.rockgympro.com/b/?bo=662996ead0ed4e7691cf8709f3bb3ca1", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://altitudegym.ca/en/orleans/courses/recreational-courses/", "https://app.rockgympro.com/b/?bo=662996ead0ed4e7691cf8709f3bb3ca1"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 155, venue_id: 41, title: "Recreational Climbing Level 1 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Once-weekly seven-week course teaching fundamental climbing skills (pink boulder level) for ages 8-13", schedule_kind: "course", start_date: ~D[2026-09-07], end_date: ~D[2026-10-22], start_time: ~T[17:30:00], end_time: ~T[19:00:00], audience: ["youth"], ages: "Ages 8-13 (14-17 advertised)", link: "https://app.rockgympro.com/b/?bw=dde41f24f67a4bb59545f5b77e34d2ff", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://altitudegym.ca/en/orleans/courses/recreational-courses/", "https://app.rockgympro.com/b/?bo=540bd714191a4cb4a91bb3831e3dfac2", "https://app.rockgympro.com/b/?bo=18623a026c214cf8916a340ca2da535b"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 156, venue_id: 41, title: "Recreational Climbing Level 2 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Once-weekly seven-week course refining climbing skills on pink and yellow boulders for ages 8-13", schedule_kind: "course", start_date: ~D[2026-09-08], end_date: ~D[2026-10-21], start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 8-13 (14-17 advertised)", link: "https://app.rockgympro.com/b/?bw=dde41f24f67a4bb59545f5b77e34d2ff", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://altitudegym.ca/en/orleans/courses/recreational-courses/", "https://app.rockgympro.com/b/?bo=335ffdddcba84846a8517f715eb3780e", "https://app.rockgympro.com/b/?bo=52d7e89fcb844299872741a91fdc797d"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 157, venue_id: 41, title: "Recreational Climbing Level 3 — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Twice-weekly advanced course on yellow and green boulders for ages 8-13 preparing climbers for team development", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 8-13", link: "https://app.rockgympro.com/b/?bo=2b5f8975eaa54a5da51e09c0a318e11f", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://altitudegym.ca/en/orleans/courses/recreational-courses/", "https://app.rockgympro.com/b/?bo=2b5f8975eaa54a5da51e09c0a318e11f"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 158, venue_id: 41, title: "Adult Beginner Recreational Course — September 2026", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Seven-week beginner climbing course for adults with a 1:8 instructor ratio and a minimum of six participants.", schedule_kind: "course", start_date: ~D[2026-09-07], end_date: ~D[2026-10-19], start_time: ~T[19:15:00], end_time: ~T[21:15:00], audience: ["adult"], ages: "Adults", link: "https://app.rockgympro.com/b/?bo=adfe8701b2c54e9a8c86244ffb55f0d0", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://altitudegym.ca/en/orleans/courses/recreational-courses/", "https://app.rockgympro.com/b/?bo=adfe8701b2c54e9a8c86244ffb55f0d0"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 97, venue_id: 13, title: "Intro to Bouldering", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "One-hour beginner session covering safety, falling, problem reading and basic climbing", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=2c2f33f180d34210a2e5def9237ec636&mode=p", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://rockhausclimbing.com/intro-to-bouldering", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=2c2f33f180d34210a2e5def9237ec636&mode=p"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 98, venue_id: 13, title: "Bouldering 101", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Technique class for V1-V3 climbers: body positioning, footwork, route reading, mental approach, drills and personalized feedback.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=a2ffc7275641414d8b9f9d3503d77347&mode=p", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://rockhausclimbing.com/bouldering-101", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=a2ffc7275641414d8b9f9d3503d77347&mode=p"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 99, venue_id: 13, title: "Mini Boulder Crushers — September cohort", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Eight-week coached bouldering for ages 8-12 building fundamentals, movement, confidence, coordination and teamwork.", schedule_kind: "one_off", start_date: ~D[2026-09-09], end_date: nil, start_time: ~T[17:00:00], end_time: ~T[18:00:00], audience: ["youth"], ages: "Ages 8-12", link: "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=c951257bd36c485c97d86752e8214aae&mode=p", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://rockhausclimbing.com/mini-crushers-age-8-12", "https://app.rockgympro.com/b/widget/?a=offering&offering_guid=c951257bd36c485c97d86752e8214aae&mode=p"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-09], start_time: ~T[17:00:00], end_time: ~T[18:00:00]}])
put!.(%{id: 100, venue_id: 13, title: "Student Tuesday", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Students over 18 need valid student ID and must be under 22.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: "Under 22 (students)", link: "https://rockhausclimbing.com/specials", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://rockhausclimbing.com/specials"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 8, venue_id: 15, title: "Yoga at the Parc", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Small-group yoga for all levels, ages 12+.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 12+", link: "https://app.rockgympro.com/b/?&bo=68ab209cbbe941d5bff935fc4789f9d3", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.boulderparc.com/yoga", "https://www.instagram.com/boulderparc/reel/DcMRFD5RIm8/", "https://app.rockgympro.com/b/?bo=68ab209cbbe941d5bff935fc4789f9d3"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 225, venue_id: 15, title: "SPARK: Intro to Bouldering — ongoing classes", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Two-hour intro to bouldering for new climbers aged 16+ and climbing at V0–V3.", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 16+", link: "https://app.rockgympro.com/b/?bo=e92a0a9b2dfe45cb823cbfdc761bac9e", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.boulderparc.com/", "https://app.rockgympro.com/b/?bo=e92a0a9b2dfe45cb823cbfdc761bac9e"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 226, venue_id: 15, title: "FUEL: The Next Step in Bouldering — September 2026 classes", kind: "class", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Two-hour next-step bouldering class for ages 16+ comfortable on V2-V3 and aiming for V4+: advanced hand/foot matching, roofs, slabs, volumes and climbing-specific strength.", schedule_kind: "one_off", start_date: ~D[2026-09-12], end_date: nil, start_time: nil, end_time: nil, audience: ["youth"], ages: "Ages 16+", link: "https://app.rockgympro.com/b/?bo=ce7bbf9b1b8f4a5f8d28a3eff228497b", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.boulderparc.com/", "https://app.rockgympro.com/b/?bo=ce7bbf9b1b8f4a5f8d28a3eff228497b"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-09-12]}])
put!.(%{id: 9, venue_id: 46, title: "Speed Provincials Qualifiers", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "OCF speed qualifying competition for U13 through senior categories.", schedule_kind: "one_off", start_date: ~D[2026-11-22], end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.boilerroom.ca/kingston-events.html", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.boilerroom.ca/kingston-events.html", "https://www.climbontario.ca/events/ocf-speed-u13-u15-u17-u19-u21-sr", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2026-11-22]}])
put!.(%{id: 10, venue_id: 46, title: "Speed Provincials", kind: "competition", ocf: true, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "OCF speed provincial championship for U13 through senior categories.", schedule_kind: "one_off", start_date: ~D[2027-01-10], end_date: nil, start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.boilerroom.ca/kingston-events.html", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.boilerroom.ca/kingston-events.html", "https://www.climbontario.ca/events/ocf-speed-provincials-u13-u15-u17-u19-u21-sr", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2027-01-10]}])
put!.(%{id: 11, venue_id: 46, title: "Canadian National Championship — Boulder and Lead", kind: "competition", ocf: false, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Canadian boulder and lead national championships announced for this venue", schedule_kind: "multi_day", start_date: ~D[2027-02-12], end_date: ~D[2027-02-16], start_time: nil, end_time: nil, audience: [], ages: nil, link: "https://www.boilerroom.ca/kingston-events.html", link_kind: "event", confidence: "tentative", caveat: nil, sources: ["https://www.boilerroom.ca/kingston-events.html", "https://www.instagram.com/boilerroomclimbing/p/DcMJDXESyvx/", "https://www.climbontario.ca/events"], checked_on: ~D[2026-09-07], published: false}, [~D[2027-02-12], ~D[2027-02-16] ])
put!.(%{id: 204, venue_id: 35, title: "No Boys Allowed — monthly climbing social", kind: "social", ocf: nil, cohorts: [], timezone: "America/Toronto", location_kind: "venue", summary: "Monthly climbing social to climb, chill and chat", schedule_kind: "unscheduled", start_date: nil, end_date: nil, start_time: nil, end_time: nil, audience: ["family"], ages: nil, link: "https://www.instagram.com/windsorrockgym/reel/DYibwHDu3b5/", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://www.instagram.com/windsorrockgym/reel/DYibwHDu3b5/"], checked_on: ~D[2026-09-06], published: false}, [])
