alias ClimbOntario.Catalogue.Import
m = Jason.decode!(File.read!("/workspace/dot-files/knowledge/ontario-gyms/luna-conversion-assignments.json"))
allowed = (m["3"]["first_ten"] ++ m["3"]["remaining_ids"]) |> Enum.map(fn x -> if is_map(x), do: x["id"], else: x end) |> MapSet.new()
targets = [305, 117, 119, 122, 124, 125, 126, 303]
unless Enum.all?(targets, &MapSet.member?(allowed, &1)), do: raise "target outside worker 3 manifest"
put! = fn a, s -> case Import.put_listing(a, s) do {:ok,l}->IO.puts("repaired #{l.id}: #{length(l.occurrences)}"); {:error,c}->IO.inspect(c); raise "failed" end end
tz = "America/Toronto"
put!.(%{id: 305, venue_id: 22, title: "OCF Top Rope U11/ U13/ U15 — 2027-02-13", kind: "competition", ocf: true, cohorts: [], timezone: tz, location_kind: "venue", summary: "Official OCF top-rope competition for U11, U13 and U15 climbers.", schedule_kind: "one_off", start_date: ~D[2027-02-13], end_date: ~D[2027-02-13], audience: ["youth"], ages: "U11, U13 and U15.", link: "https://www.climbontario.ca/events/ocf-tope-rope-u11-u13-u15", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-tope-rope-u11-u13-u15", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2027-02-13]}])
put!.(%{id: 117, venue_id: 21, title: "Reach Progression — Fall 2026", kind: "class", ocf: nil, cohorts: [], timezone: tz, location_kind: "venue", summary: "Six-week intermediate bouldering course for adults.", schedule_kind: "course", start_date: ~D[2026-09-17], end_date: ~D[2026-10-22], start_time: ~T[19:30:00], end_time: ~T[21:30:00], audience: ["adult"], ages: "18+.", link: "https://app.rockgympro.com/b/?bo=42f3fd1991fa4a7292f2acaff97dafd6", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/adult-lessons", "https://app.rockgympro.com/b/?bo=42f3fd1991fa4a7292f2acaff97dafd6"], checked_on: ~D[2026-09-06], published: false}, Enum.map(~w(2026-09-17 2026-09-24 2026-10-01 2026-10-08 2026-10-15 2026-10-22), &%{date: &1}) )
put!.(%{id: 119, venue_id: 21, title: "Lead Climb and Belay Lesson", kind: "class", ocf: nil, cohorts: [], timezone: tz, location_kind: "venue", summary: "Two-session lead climbing and belay instruction for adult climbers.", schedule_kind: "unscheduled", audience: ["adult"], ages: "Ages 16+; currently climbing 5.9+.", link: "https://reachindoorclimbing.ca/skill-instruction", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/skill-instruction"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 122, venue_id: 21, title: "Performance Team", kind: "class", ocf: nil, cohorts: [], timezone: tz, location_kind: "venue", summary: "Experienced youth competition team with shared skill and practice training.", schedule_kind: "unscheduled", audience: ["youth"], ages: "Birth years 2009–2013.", link: "https://reachindoorclimbing.ca/competitive-teams", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/competitive-teams"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 124, venue_id: 21, title: "Private, Semi-Private and Group Coaching", kind: "class", ocf: nil, cohorts: [], timezone: tz, location_kind: "venue", summary: "Climbing coaching tailored to personal goals, training plans, technique and progression.", schedule_kind: "unscheduled", audience: [], ages: nil, link: "https://reachindoorclimbing.ca/private-lessons", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/private-lessons"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 125, venue_id: 21, title: "Therapeutic and Adaptive Climbing Sessions", kind: "class", ocf: nil, cohorts: [], timezone: tz, location_kind: "venue", summary: "Occupational-therapist-supported adaptive climbing for children and adults.", schedule_kind: "unscheduled", audience: ["adaptive", "youth", "adult"], ages: "Children and adults.", link: "https://reachindoorclimbing.ca/therapy%2Fadaptive-climbing", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://reachindoorclimbing.ca/therapy%2Fadaptive-climbing"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 126, venue_id: 21, title: "Friday Night Onsight — October 2026", kind: "competition", ocf: false, cohorts: [], timezone: tz, location_kind: "venue", summary: "Recreational competition climbing night.", schedule_kind: "one_off", start_date: ~D[2026-10-02], end_date: ~D[2026-10-02], start_time: ~T[18:00:00], end_time: ~T[21:00:00], audience: [], link: "https://app.rockgympro.com/b/?bo=a30bb04fadbd471fb97cb9060422bdcc", link_kind: "registration", confidence: "confirmed", caveat: nil, sources: ["https://app.rockgympro.com/b/?bo=a30bb04fadbd471fb97cb9060422bdcc", "https://linktr.ee/reachindoorclimbing", "https://www.instagram.com/reachindoorclimbing/p/Dcl5K0FOvch/"], checked_on: ~D[2026-09-06], published: false}, [%{date: ~D[2026-10-02], start_time: ~T[18:00:00], end_time: ~T[21:00:00]}])
put!.(%{id: 303, venue_id: 21, title: "OCF Boulder U11/ U13/ U15 — 2026-12-12", kind: "competition", ocf: true, cohorts: ["U11/U13 — Saturday", "U15 — Sunday"], timezone: tz, location_kind: "venue", summary: "Official OCF bouldering competition for youth categories.", schedule_kind: "multi_day", start_date: ~D[2026-12-12], end_date: ~D[2026-12-13], audience: ["youth"], ages: "U11, U13 and U15.", link: "https://www.climbontario.ca/events/ocf-boulder-u11-u13-u15", link_kind: "event", confidence: "confirmed", caveat: nil, sources: ["https://www.climbontario.ca/events/ocf-boulder-u11-u13-u15", "https://www.climbontario.ca/news/ocf-2026-27-competition-season"], checked_on: ~D[2026-09-07], published: false}, [%{date: ~D[2026-12-12], cohort: "U11/U13 — Saturday"}, %{date: ~D[2026-12-13], cohort: "U15 — Sunday"}])
IO.puts("explicit batch 3.2 complete")
