alias ClimbOntario.Catalogue.Import
m=Jason.decode!(File.read!("/workspace/dot-files/knowledge/ontario-gyms/luna-conversion-assignments.json")); allowed=(m["3"]["first_ten"]++m["3"]["remaining_ids"])|>Enum.map(fn x->if is_map(x), do: x["id"], else: x end)|>MapSet.new(); targets=[71,72,73,74,75,76,77,78,79,80,81,82,83,84,85]; unless Enum.all?(targets,&MapSet.member?(allowed,&1)), do: raise "outside manifest"
put!=fn a,s->case Import.put_listing(a,s) do {:ok,l}->IO.puts("repaired #{l.id}:#{length(l.occurrences)}"); {:error,c}->IO.inspect(c);raise "failed" end end
tz="America/Toronto"
base=fn id,title,kind,summary,sk,extra,aud,ages,url,link_kind,src -> venue_id=if id <= 77, do: 2, else: 3; put!.(Map.merge(%{id: id, venue_id: venue_id,title: title,kind: kind,timezone: tz,location_kind: "venue",summary: summary,schedule_kind: sk,audience: aud,ages: ages,link: url,link_kind: link_kind,confidence: "confirmed",sources: src,checked_on: ~D[2026-09-06],published: false},extra), :preserve) end
base.(71,"Core Elements — Intro to Bouldering","class","90-minute beginner bouldering class covering footwork, dynamic movement and body positioning.","one_off",%{start_date: ~D[2026-09-06],end_date: ~D[2026-09-06],start_time: ~T[16:00:00],end_time: ~T[17:30:00]},[],nil,"https://ethosclimbing.rphq.com/ethos/programs/meet-climbing","registration",["https://www.ethosclimbing.ca/instruction","https://ethosclimbing.rphq.com/ethos/programs/meet-climbing"])
base.(72,"Kilter Class","class","Drop-in guided training on the adjustable Kilter Board with personalized feedback.","recurring",%{recurrence: "weekly",weekday: 6,start_time: ~T[13:00:00],end_time: ~T[14:00:00]},[],nil,"https://ethosclimbing.rphq.com/ethos/n/classes","registration",["https://www.ethosclimbing.ca/instruction","https://ethosclimbing.rphq.com/ethos/programs/Kilter%20Class?date=2026-09-12","https://ethosclimbing.rphq.com/ethos/programs/kilter-class?date=2026-09-19"])
base.(73,"Sunday School — Coached Climbing","class","Coached Sunday climbing session with project support, feedback and technique coaching.","recurring",%{recurrence: "weekly",weekday: 7,start_time: ~T[13:00:00],end_time: ~T[14:00:00]},[],nil,"https://ethosclimbing.rphq.com/ethos/n/classes","registration",["https://www.ethosclimbing.ca/instruction","https://ethosclimbing.rphq.com/ethos/programs/sunday-school?date=2026-09-13","https://ethosclimbing.rphq.com/ethos/programs/sunday-school-2?date=2026-09-20","https://www.instagram.com/ethosclimbinggym/reel/DckDPY-MbAO/"])
base.(74,"Elevate — Goal Setting and Session Planning Clinic","class","Climbing goal-setting and session-planning clinic for women and gender-diverse climbers.","one_off",%{start_date: ~D[2026-09-14],end_date: ~D[2026-09-14],start_time: ~T[19:00:00],end_time: ~T[21:00:00]},["women","queer"],nil,"https://www.instagram.com/ethosclimbinggym/p/DcuF_rSxt1q/","event",["https://www.instagram.com/ethosclimbinggym/p/DcuF_rSxt1q/"])
base.(75,"Ethos Queer Climb","social","Weekly queer social climbing club for all experience levels.","recurring",%{recurrence: "weekly",weekday: 3,start_time: ~T[19:00:00]},["queer"],nil,"https://www.instagram.com/ethosclimbinggym/p/Dbq_y-NGZIP/","event",["https://www.instagram.com/ethosclimbinggym/p/Dbq_y-NGZIP/","https://www.ethosclimbing.ca/"])
base.(76,"Queer Climb Toronto Meetup — September 2026","social","All-level queer and trans bouldering meetup.","one_off",%{start_date: ~D[2026-09-13],end_date: ~D[2026-09-13],start_time: ~T[14:00:00],end_time: ~T[17:00:00]},["queer"],nil,"https://portal.ethosclimbing.ca/l?t=JoZPu2TszEKxxBVQ","registration",["https://www.instagram.com/ethosclimbinggym/p/DceSVV9ykzH/","https://portal.ethosclimbing.ca/l?t=JoZPu2TszEKxxBVQ"])
base.(77,"Private Climbing Coaching with Brad","class","One-on-one goal-setting and tailored climbing coaching.","unscheduled",%{},[],nil,"https://www.ethosclimbing.ca/instruction","event",["https://www.ethosclimbing.ca/instruction"])
base.(78,"Bouldering 101","class","One-hour beginner bouldering class covering safety, falling, problem reading and basic technique.","recurring",%{recurrence: "weekly",weekday: 7,start_time: ~T[10:00:00],end_time: ~T[11:00:00]},[],nil,"https://www.rockonclimbing.ca/bouldering-101-class","registration",["https://www.rockonclimbing.ca/bouldering-101-class", "https://www.rockonclimbing.ca/promos"])
base.(79,"Bouldering 102 — September 2026","class","Five-week beginner bouldering programme covering technique and movement.","recurring",%{recurrence: "weekly",weekday: 6,start_date: ~D[2026-09-12],start_time: ~T[13:00:00],end_time: ~T[15:00:00]},[],nil,"https://www.instagram.com/rockon_to/p/DchXH4rtxR3/","registration",["https://www.instagram.com/rockon_to/p/DchXH4rtxR3/"])
base.(80,"Bouldering 201","class","Five-week technique and plateau-breaking course for developing climbers.","unscheduled",%{},[],nil,"https://www.rockonclimbing.ca/bouldering-101-class","registration",["https://www.rockonclimbing.ca/bouldering-101-class"])
base.(81,"Private Climbing Coaching","class","Customized one-on-one climbing coaching tailored to individual abilities.","unscheduled",%{},[],nil,"https://www.rockonclimbing.ca/bouldering-101-class","registration",["https://www.rockonclimbing.ca/bouldering-101-class"])
base.(82,"Community Trivia Nights","social","Community trivia night hosted by Kels.","unscheduled",%{},["family"],nil,"https://www.rockonclimbing.ca/promos","event",["https://www.rockonclimbing.ca/promos","https://www.instagram.com/rockon_to/p/DW2Gx9rgWY_/","https://www.instagram.com/rockon_to/p/DZYWZp_BssD/"])
base.(83,"Mat Leave Mondays","social","Weekly climbing and connection session for parents with babies.","recurring",%{recurrence: "weekly",weekday: 1,start_time: ~T[09:00:00],end_time: ~T[12:00:00]},["family"],nil,"https://www.rockonclimbing.ca/promos","event",["https://www.rockonclimbing.ca/promos"])
base.(84,"Community Climb with Jenny","social","Weekly casual climbing session alongside coach Jenny.","recurring",%{recurrence: "weekly",weekday: 7,start_time: ~T[16:00:00],end_time: ~T[20:00:00]},[],nil,"https://www.rockonclimbing.ca/promos","event",["https://www.rockonclimbing.ca/promos"])
base.(85,"Student Saturdays","social","Weekly Saturday climbing offer for students.","recurring",%{recurrence: "weekly",weekday: 6},[],"Students","https://www.rockonclimbing.ca/promos","event",["https://www.rockonclimbing.ca/promos"])
IO.puts("explicit batch 3.4 complete")
