alias ClimbOntario.Catalogue.Import
m = Jason.decode!(File.read!("/workspace/dot-files/knowledge/ontario-gyms/luna-conversion-assignments.json"))
allowed = (m["3"]["first_ten"] ++ m["3"]["remaining_ids"]) |> Enum.map(fn x -> if is_map(x), do: x["id"], else: x end) |> MapSet.new()
targets = [116, 118, 120, 121, 123]
unless Enum.all?(targets, &MapSet.member?(allowed, &1)), do: raise "target outside worker 3 manifest"
put! = fn a, s -> case Import.put_listing(a, s) do {:ok, l} -> IO.puts("converted #{l.id}: #{length(l.occurrences)} occurrences"); {:error, c} -> IO.inspect(c); raise "failed" end end
tz = "America/Toronto"
reach = "https://reachindoorclimbing.ca"
put!.(%{id: 116, venue_id: 21, title: "Reach Fundamentals — Fall 2026", kind: "class", timezone: tz, location_kind: "venue", summary: "Six-week adult fundamentals course covering climbing technique and movement.", schedule_kind: "course", start_date: ~D[2026-09-15], end_date: ~D[2026-10-20], start_time: ~T[19:30:00], end_time: ~T[21:30:00], audience: ["adult"], ages: "18+.", link: "https://app.rockgympro.com/b/?bo=a8d32f34e6d5451b8cd71d50d1ce5bc4", link_kind: "registration", confidence: "confirmed", sources: ["#{reach}/adult-lessons", "https://app.rockgympro.com/b/?bo=a8d32f34e6d5451b8cd71d50d1ce5bc4"], checked_on: ~D[2026-09-06], published: false}, Enum.map(~w(2026-09-15 2026-09-22 2026-09-29 2026-10-06 2026-10-13 2026-10-20), &%{date: &1, start_time: ~T[19:30:00], end_time: ~T[21:30:00]}) )
put!.(%{id: 118, venue_id: 21, title: "Top Rope Belay Lesson and Intro PLUS", kind: "class", timezone: tz, location_kind: "venue", summary: "Introductory top-rope belay lesson and climbing orientation arranged by appointment.", schedule_kind: "unscheduled", audience: [], ages: nil, link: "#{reach}/skill-instruction", link_kind: "event", confidence: "confirmed", sources: ["#{reach}/skill-instruction"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 120, venue_id: 21, title: "Sunday Speed Training", kind: "class", cohorts: ["U13/U15 — Sunday morning", "U17/U19/U21/Senior — Sunday afternoon"], timezone: tz, location_kind: "venue", summary: "Sunday speed-training sessions for youth and adult competition categories.", schedule_kind: "recurring", audience: ["youth", "adult"], ages: "U13 through Senior.", link: "#{reach}/skill-instruction", link_kind: "event", confidence: "confirmed", sources: ["#{reach}/skill-instruction"], checked_on: ~D[2026-09-06], published: false}, Enum.map(~w(2026-09-13 2026-09-20 2026-09-27), &%{date: &1, cohort: "U13/U15 — Sunday morning", start_time: ~T[09:00:00], end_time: ~T[11:00:00]}) ++ Enum.map(~w(2026-09-13 2026-09-20 2026-09-27), &%{date: &1, cohort: "U17/U19/U21/Senior — Sunday afternoon", start_time: ~T[12:00:00], end_time: ~T[15:00:00]}))
put!.(%{id: 121, venue_id: 21, title: "Development Team", kind: "class", cohorts: ["Tuesday", "Thursday"], timezone: tz, location_kind: "venue", summary: "Youth development team training for experienced climbers.", schedule_kind: "unscheduled", audience: ["youth"], ages: "Ages 10–16.", link: "#{reach}/competitive-teams", link_kind: "event", confidence: "confirmed", sources: ["#{reach}/competitive-teams"], checked_on: ~D[2026-09-06], published: false}, [])
put!.(%{id: 123, venue_id: 21, title: "Adult Competition Team", kind: "class", timezone: tz, location_kind: "venue", summary: "Friday evening training team for adult competition climbers.", schedule_kind: "recurring", recurrence: "weekly", weekday: 5, start_time: ~T[18:00:00], end_time: ~T[21:00:00], audience: ["adult"], ages: "Adults.", link: "#{reach}/competitive-teams", link_kind: "event", confidence: "confirmed", sources: ["#{reach}/competitive-teams"], checked_on: ~D[2026-09-06], published: false}, [])
IO.puts("explicit batch 3.7 complete")
