alias ClimbOntario.Catalogue.Import
m=Jason.decode!(File.read!("/workspace/dot-files/knowledge/ontario-gyms/luna-conversion-assignments.json")); allowed=(m["3"]["first_ten"]++m["3"]["remaining_ids"])|>Enum.map(fn x->if is_map(x),do: x["id"],else: x end)|>MapSet.new(); targets=[132,133,134,135,306,307]; unless Enum.all?(targets,&MapSet.member?(allowed,&1)),do: raise "target outside manifest"
put!=fn a,s->case Import.put_listing(a,s) do {:ok,l}->IO.puts("converted #{l.id}: #{length(l.occurrences)} occurrences"); {:error,c}->IO.inspect(c);raise "failed" end end
tz="America/Toronto"
base=fn id,title,summary,ages,url -> put!.(%{id: id,venue_id: 24,title: title,kind: "class",timezone: tz,location_kind: "venue",summary: summary,schedule_kind: "unscheduled",audience: [],ages: ages,link: url,link_kind: "event",confidence: "confirmed",sources: [url],checked_on: ~D[2026-09-06],published: false},[]) end
base.(132,"Adult Climbing Course — Rolling Four Weeks","Rolling four-week adult climbing course advertised on Wednesdays; exact enrollment start must be confirmed.","Adults.","https://www.pinnacleclimbing.ca/programs")
base.(133,"Pinnacle Climbing Academy — Rolling Youth Programme","Ongoing four-class youth programme with age-grouped Wednesday and Saturday offerings.","Ages 4–13.","https://www.pinnacleclimbing.ca/programs")
base.(134,"Pinnacle Prep Team — September to May","Nine-month youth prep team programme with twice-weekly group options; exact start and hours unpublished.","Youth climbers.","https://www.instagram.com/pinnacleclimbing/p/Dc9xqW0R0Vx/")
base.(135,"Pinnacle Comp Team — Invitation/Tryout","Invitation and contact-arranged tryout pathway for the competitive team.","Youth competition climbers.","https://www.instagram.com/pinnacleclimbing/p/Dc9xqW0R0Vx/")
put!.(%{id: 306,venue_id: 24,title: "OCF Top Rope U11/ U13/ U15 — 2026-10-25",kind: "competition",ocf: true,timezone: tz,location_kind: "venue",summary: "Official OCF top-rope competition for U11, U13 and U15 climbers.",schedule_kind: "one_off",start_date: ~D[2026-10-25],end_date: ~D[2026-10-25],audience: ["youth"],ages: "U11, U13 and U15.",link: "https://www.climbontario.ca/events/ocf-u11-u13-u15-tope-rope",link_kind: "event",confidence: "confirmed",sources: ["https://www.climbontario.ca/events/ocf-u11-u13-u15-tope-rope","https://www.climbontario.ca/news/ocf-2026-27-competition-season"],checked_on: ~D[2026-09-07],published: false},[%{date: ~D[2026-10-25]}])
put!.(%{id: 307,venue_id: 24,title: "OCF SPEED U13/ U15 U17/ U19/ U21 /SR — 2026-11-08",kind: "competition",ocf: true,timezone: tz,location_kind: "venue",summary: "Official OCF speed competition for youth and senior categories.",schedule_kind: "one_off",start_date: ~D[2026-11-08],end_date: ~D[2026-11-08],audience: ["youth","adult"],ages: "U13, U15, U17, U19, U21 and Senior.",link: "https://www.climbontario.ca/events/ocf-speed-u11-u13-u15-u17-u19-u21-sr",link_kind: "event",confidence: "confirmed",sources: ["https://www.climbontario.ca/events/ocf-speed-u11-u13-u15-u17-u19-u21-sr","https://www.climbontario.ca/news/ocf-2026-27-competition-season"],checked_on: ~D[2026-09-07],published: false},[%{date: ~D[2026-11-08]}])
IO.puts("explicit batch 3.9 complete")
